basedbook/basedbook_website/apps/accounts/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [

    path('profile', views.ProfileView.as_view(), name="profile"),



    #Django auth stuff
    path('login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout")
]###      ^ACCOUNTS/

basedbook/basedbook_website/urls.py
from django.contrib import admin
from django.urls import path, include
#from . import views
#from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basedbook_website.apps.public.urls')),

    path('accounts/', include('basedbook_website.apps.accounts.urls' )),



    #Django auth stuff
    #path('accounts/login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    #path('accounts/logout', auth_views.LogoutView.as_view(), name="logout")
]


basedbook/basedbook_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name



class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    #owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    #settings
    is_full_name_displayed = models.BooleanField(default=True)


    #details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

basedbook/basedbook_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

basedbook/basedbook_website/templates/about.html
{% extends 'base.html'%}


{% block title %}About{% endblock%}


{% block content %}
<h1>
    Template Homepage I think i can put what ever I want here?
    yup
    a';psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG

ADKRFJGNSAKDLJGBKLAJBEFLKJbeflkjbaref
THIS SHOULD BE THE ABOUT PAGE


</h1>

{% endblock%}

basedbook/basedbook_website/templates/accounts/login.html
{% extends 'base.html'%}


{% block title %}Login{% endblock%}


{% block content %}
<h2>Login</h2>
<form method="post">
    {%csrf_token%}
    {{ form.as_p}}
    <button type="submit">Login</button>
</form>

{% endblock%}

basedbook/basedbook_website/templates/accounts/profile.html
{% extends 'base.html'%}


{% block title %}PROFILE{% endblock%}


{% block content %}

<h1>
    {{user.get_full_name}} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:""}}
        </h2>
        <div>
            {{profile.bio|default:""}}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{website}}">{{website}}</a>
            {% endwith%}
        </div>
        <br/>
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>
                    {{interest.name }}{% if not forloop.last %}, {% endif %}
                </span>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}







{% endblock%}

basedbook/basedbook_website/templates/base.html
<!-- templates/base.html-->
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Based Book{% endblock%}</title>


        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />


        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />

        <link href="{% static 'cssMine/main.css' %}" rel="stylesheet" />

    </head>
    <body>
        {% include 'navbar.html'%}
        <main id="main">
            {% block content %}
            {% endblock%}

        </main>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'theme/js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

basedbook/basedbook_website/templates/contact.html
{% extends 'base.html'%}


{% block title %}Contact{% endblock%}


{% block content %}
<h1>
    Template Homepage I think i can put what ever I want here?
    yup
    a';psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG

ADKRFJGNSAKDLJGBKLAJBEFLKJbeflkjbaref

IN THE CONTACT PAGE

;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 1
;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 2
;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 3
;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 4
;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 5
;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 6
;psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG 7


</h1>

{% endblock%}

basedbook/basedbook_website/templates/index.html
{% extends 'base.html'%}
{% load static %}


{% block title %}home{% endblock%}


{% block content %}

<h1>
    Template Homepage I think i can put what ever I want here?
    yup
    a';psdfj;lakderfglkp;jasdvkljbsdt;lkbnaL;KSBFL;KJADEBFG

ADKRFJGNSAKDLJGBKLAJBEFLKJbeflkjbaref

</h1>

{% endblock%}

basedbook/basedbook_website/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">Based Book</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">

                {% url 'public:index' as index_url %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == index_url %}active{% endif %}" href="{% url 'public:index' %}">Home</a></li>
                {% url 'public:about' as about_url %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == about_url %}active{% endif %}" href="{% url 'public:about' %}">About</a></li>
                {% url 'public:contact' as contact_url %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == contact_url %}active{% endif %}" href="{% url 'public:contact' %}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

<!--
<div>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %} Home {% else %}<a href="{% url 'public:index' %}"> Home</a>{% endif %} </span>


    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %} About {% else %}<a href="{% url 'public:about' %}"> About</a>{% endif %} </span>


    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %} Contact {% else %}<a href="{% url 'public:contact' %}"> Contact</a>{% endif %} </span>

    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}

            <span> HI {% if request.path == profile_url %}{{ user.username}}{% else %} <a href="{{ profile_url }}">{{user.username}}</a>{% endif %}!</span>

        <span><a href="{% url 'accounts:logout' %}">logout</a></span>
        {% else %}
        <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif%}
    </span>
</div>
-->